services:
  - type: web
    plan: free
    name: Scorpion 
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 ser.py & bash start
    region: frankfurt #frankfurt #Singapore
    envVars:
      - key: API_ID 
        value: 9514755
      - key: API_HASH 
        value: 40e7041d06ea7b6ee1cf39b3188b3452
      - key: BOT_TOKEN 
        value: 7360356871:AAE6IYZH2gfGOe4cG2CM1UxRn90ATjLkvJE
      - key: OWNER_ID 
        value: 7275336620
      - key: MONGO_DB_URI
        value: mongodb+srv://Hamodey2006:Hamodey2006@cluster0.xilnp5n.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
